name: "release-v6-builder-runner"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        required: true
        default: 'master'
      version:
        description: 'version'
        required: true
        default: 'stable'
      
env:
  VERSION: ${{ github.event.inputs.version }}
  
jobs:
  builder:
    runs-on: ubuntu-latest
    environment: release-v6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: goodrain/builder
          ref: ${{ github.event.inputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          password: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}

      - name: Set release description
        run: |
          buildTime=$(date +%F-%H)
          git_commit=$(git log -n 1 --pretty --format=%h)
          release_desc="${{ env.VERSION }}-${git_commit}-${buildTime}"
          echo "release_desc=$release_desc" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            RELEASE_DESC=${{ env.release_desc }}
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            rainbond/builder:${{ env.VERSION }}
            registry.cn-hangzhou.aliyuncs.com/goodrain/builder:${{ env.VERSION }}

  runner:
    runs-on: ubuntu-latest
    environment: release-v6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: goodrain/runner
          ref: ${{ github.event.inputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          password: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}

      - name: Set release description
        run: |
          buildTime=$(date +%F-%H)
          git_commit=$(git log -n 1 --pretty --format=%h)
          release_desc="${{ env.VERSION }}-${git_commit}-${buildTime}"
          echo "release_desc=$release_desc" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            RELEASE_DESC=${{ env.release_desc }}
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            rainbond/runner:${{ env.VERSION }}
            registry.cn-hangzhou.aliyuncs.com/goodrain/runner:${{ env.VERSION }}